In [1]:
pip install rdkit

Collecting rdkit
  Downloading rdkit-2025.9.6-cp313-cp313-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: numpy in c:\users\ds\miniconda3\lib\site-packages (from rdkit) (2.4.3)
Requirement already satisfied: Pillow in c:\users\ds\miniconda3\lib\site-packages (from rdkit) (12.1.1)
Downloading rdkit-2025.9.6-cp313-cp313-win_amd64.whl (24.3 MB)
   ---------------------------------------- 0.0/24.3 MB ? eta -:--:--
   --- ------------------------------------ 2.4/24.3 MB 18.4 MB/s eta 0:00:02
   ------- -------------------------------- 4.5/24.3 MB 13.2 MB/s eta 0:00:02
   -------- ------------------------------- 5.2/24.3 MB 10.5 MB/s eta 0:00:02
   ---------- ----------------------------- 6.3/24.3 MB 8.8 MB/s eta 0:00:03
   ------------ --------------------------- 7.3/24.3 MB 7.9 MB/s eta 0:00:03
   ------------- -------------------------- 8.4/24.3 MB 7.4 MB/s eta 0:00:03
   --------------- ------------------------ 9.4/24.3 MB 7.0 MB/s eta 0:00:03
   ----------------- ---------------------- 10.5/24.3 MB 6.7 MB/s eta 0:00:03
   ------------------ --------------------- 11.5/24.3 MB 6.5 MB/s eta 0:00:02
   -------------------- ------------------- 12.6/24.3 MB 6.4 MB/s eta 0:00:02
   ---------------------- ----------------- 13.6/24.3 MB 6.2 MB/s eta 0:00:02
   ------------------------ --------------- 14.7/24.3 MB 6.1 MB/s eta 0:00:02
   ------------------------- -------------- 15.7/24.3 MB 6.0 MB/s eta 0:00:02
   --------------------------- ------------ 16.8/24.3 MB 6.0 MB/s eta 0:00:02
   ----------------------------- ---------- 17.8/24.3 MB 5.9 MB/s eta 0:00:02
   ------------------------------- -------- 18.9/24.3 MB 5.8 MB/s eta 0:00:01
   -------------------------------- ------- 19.9/24.3 MB 5.8 MB/s eta 0:00:01
   ---------------------------------- ----- 21.0/24.3 MB 5.7 MB/s eta 0:00:01
   ------------------------------------ --- 22.0/24.3 MB 5.7 MB/s eta 0:00:01
   ------------------------------------- -- 23.1/24.3 MB 5.7 MB/s eta 0:00:01
   ---------------------------------------  24.1/24.3 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 24.3/24.3 MB 5.5 MB/s  0:00:04
Installing collected packages: rdkit
Successfully installed rdkit-2025.9.6
Note: you may need to restart the kernel to use updated packages.

In [12]:
import pandas as pd
from rdkit import Chem
from rdkit.Chem import Descriptors

In [13]:
df = pandas.read_csv('skin_irritation_cleaned.csv')
df.shape

(81, 26)

In [14]:
df.columns

Index(['Record_ID', 'Data_Type', 'Formulation_ID', 'Formulation_Name',
       'Chemical_Name', 'CASRN', 'DTXSID', 'Percent_Active_Ingredient',
       'Concentration', 'Concentration_Units', 'Mixture', 'Species',
       'Reported_Strain', 'Strain', 'Sex', 'Assay', 'Endpoint', 'Response',
       'Response_Unit', 'Reference', 'SMILES', 'Preferred_Name', 'Synonyms',
       'URL_CompTox', 'URL_CEBS', 'label'],
      dtype='str')

In [15]:
desc_total = []
for index, row in df.iterrows():
    smi = row['SMILES']
    mol = Chem.MolFromSmiles(smi)
    desc = Descriptors.CalcMolDescriptors(mol)
    desc_total.append(desc)

In [16]:
df_desc = pandas.DataFrame(desc_total)

In [17]:
df_desc

,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,HeavyAtomMolWt,ExactMolWt,NumValenceElectrons,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
0,8.111111,8.111111,0.138889,-0.560185,0.435835,15.000000,76.095,68.031,76.052429,32,...,0,0,0,0,0,0,0,0,0,0
1,9.768009,9.768009,0.750000,0.750000,0.395123,9.125000,114.188,100.076,114.104465,48,...,0,0,0,0,0,0,0,0,4,0
2,11.291588,11.291588,0.027971,-0.036181,0.319642,10.947368,270.457,236.185,270.255880,114,...,0,0,0,0,0,0,0,0,10,0
3,8.086250,8.086250,0.027778,0.027778,0.540974,8.888889,136.191,120.063,136.109944,58,...,0,0,0,0,0,0,0,0,0,0
4,0.000000,0.000000,0.000000,0.000000,0.262038,0.000000,39.997,38.989,39.992509,8,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,5.342083,5.342083,0.178241,0.178241,0.631655,12.857143,202.338,176.130,202.193280,86,...,0,0,0,0,0,0,0,0,0,0
77,11.980971,11.980971,0.366551,0.366551,0.646478,23.125000,218.340,196.164,218.167065,88,...,0,0,0,0,0,0,0,0,0,0
78,8.609759,8.609759,0.372449,0.372449,0.467641,10.800000,214.393,184.153,214.229666,92,...,0,0,0,0,0,0,0,0,11,0
79,10.524585,10.524585,0.000000,-1.489874,0.346448,9.727273,336.208,322.096,336.054554,114,...,0,0,0,0,0,0,0,0,0,0
80,11.332596,11.332596,0.027289,-0.034192,0.257436,11.047619,298.511,260.207,298.287180,126,...,0,0,0,0,0,0,0,0,12,0

In [18]:
df_id = df[['Chemical_Name','SMILES','label']]

In [19]:
df_final = pandas.concat([df_id,df_desc],axis=1) #axis를 0으로 하면 어떻게 결과가 바뀔까?

In [20]:
df_final #2D descriptor를 csv file로 저장

,Chemical_Name,SMILES,label,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
0,Propylene glycol,CC(O)CO,0,8.111111,8.111111,0.138889,-0.560185,0.435835,15.000000,76.095,...,0,0,0,0,0,0,0,0,0,0
1,Heptanal,CCCCCCC=O,1,9.768009,9.768009,0.750000,0.750000,0.395123,9.125000,114.188,...,0,0,0,0,0,0,0,0,4,0
2,Isopropyl myristate,CCCCCCCCCCCCCC(=O)OC(C)C,0,11.291588,11.291588,0.027971,-0.036181,0.319642,10.947368,270.457,...,0,0,0,0,0,0,0,0,10,0
3,di-Propylene glycol,"C*.C*.OCCOCCO |lp:4:2,7:2,10:2,m:1:5.6,3:8.9|",0,8.086250,8.086250,0.027778,0.027778,0.540974,8.888889,136.191,...,0,0,0,0,0,0,0,0,0,0
4,Sodium hydroxide,[OH-].[Na+],1,0.000000,0.000000,0.000000,0.000000,0.262038,0.000000,39.997,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,"Hexane, 3,3-bis(methoxymethyl)-2,5-dimethyl-",COCC(COC)(CC(C)C)C(C)C,1,5.342083,5.342083,0.178241,0.178241,0.631655,12.857143,202.338,...,0,0,0,0,0,0,0,0,0,0
77,1-Spiro[4.5]dec-7-en-7-yl-4-penten-1-one,C=CCCC(=O)C1=CCCC2(CCCC2)C1,0,11.980971,11.980971,0.366551,0.366551,0.646478,23.125000,218.340,...,0,0,0,0,0,0,0,0,0,0
78,1-Tetradecanol,CCCCCCCCCCCCCCO,0,8.609759,8.609759,0.372449,0.372449,0.467641,10.800000,214.393,...,0,0,0,0,0,0,0,0,11,0
79,"Ethylenediaminetetraacetic acid, disodium salt",[Na+].[Na+].OC(=O)CN(CCN(CC(O)=O)CC([O-])=O)CC...,0,10.524585,10.524585,0.000000,-1.489874,0.346448,9.727273,336.208,...,0,0,0,0,0,0,0,0,0,0
80,"Hexadecanoic acid, 1-methylethyl ester",CCCCCCCCCCCCCCCC(=O)OC(C)C,0,11.332596,11.332596,0.027289,-0.034192,0.257436,11.047619,298.511,...,0,0,0,0,0,0,0,0,12,0

In [21]:
import numpy as np
from rdkit.Chem import AllChem

fpgen = AllChem.GetRDKitFPGenerator()

fp_total = []
for index, row in df.iterrows():
    smi = row['SMILES']
    mol = Chem.MolFromSmiles(smi)
    fp = fpgen.GetFingerprint(mol)
    fp_array = np.zeros((0,), dtype=int)
    Chem.DataStructs.ConvertToNumpyArray(fp, fp_array)
    fp_total.append(fp_array)

In [22]:
df_fp = pd.DataFrame(fp_total, columns=[f'bit_{i}' for i in range(len(fp_total[0]))])

In [23]:
df_fp #Chemical_Name, SMILES, label 컬럼 추가한 뒤 별도 csv 파일로 저장

,bit_0,bit_1,bit_2,bit_3,bit_4,bit_5,bit_6,bit_7,bit_8,bit_9,...,bit_2038,bit_2039,bit_2040,bit_2041,bit_2042,bit_2043,bit_2044,bit_2045,bit_2046,bit_2047
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
77,0,0,0,0,0,0,1,0,1,0,...,0,0,0,1,0,0,0,0,0,0
78,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
79,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
80,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [24]:
# smiles 코드가 단일 구조가 아니라면 '.'이 포함되어 있음.
# 단일 구조가 아닌 물질들만 리스트를 확인하고, 제거해야 될 것과 제거하면 안되는 물질 구분해보기.
# 현재 대부분이 유기 화합물이기 때문에, 유기화합물이 염(salt)가 추가된 경우는, 염을 제거한 smiles 코드를 남겨야함.
# 무기화합물이라면 제거. 유효 성분이 몇개인지 확인이 어려운 경우도 제거.

In [25]:
#list-of-available-descriptors
#fingerprint 종류는 매우 다양, 종류별로 모두 계산해서 저장해보기

In [27]:
# smiles 코드가 단일 구조가 아니라면 '.'이 포함되어 있음.
# 단일 구조가 아닌 물질 확인

multi_smiles = df[
    df['SMILES'].str.contains(r'\.', regex=True)
]

print(multi_smiles[['Chemical_Name', 'SMILES']])

print('단일 구조가 아닌 물질 개수:', multi_smiles.shape[0])

                                        Chemical_Name  \
3                                 di-Propylene glycol
4                                    Sodium hydroxide
11                            Sodium dodecyl sulphate
12                                   Sodium carbonate
22                            Sodium xylene sulfonate
24                                Sodium percarbonate
48     Ethylenediamine tetraacetic acid disodium salt
52                                 Dipropylene glycol
57                             Sodium dodecyl sulfate
58                    Carbonic acid sodium salt (1:2)
63                             Sodium xylenesulfonate
64  Carbonic acid disodium salt, compd. with hydro...
79     Ethylenediaminetetraacetic acid, disodium salt

                                               SMILES
3       C*.C*.OCCOCCO |lp:4:2,7:2,10:2,m:1:5.6,3:8.9|
4                                         [OH-].[Na+]
11                   [Na+].CCCCCCCCCCCCOS([O-])(=O)=O
12                          [Na+].[Na+].[O-]C([O-])=O
22  C*.C*.OS(=O)(=O)C1=CC=CC=C1 |c:8,10,t:6,lp:4:2...
24  [Na+].[Na+].[Na+].[Na+].OO.OO.OO.[O-]C([O-])=O...
48  [Na+].[Na+].OC(=O)CN(CCN(CC(O)=O)CC([O-])=O)CC...
52      C*.C*.OCCOCCO |lp:4:2,7:2,10:2,m:1:5.6,3:8.9|
57                   [Na+].CCCCCCCCCCCCOS([O-])(=O)=O
58                          [Na+].[Na+].[O-]C([O-])=O
63  C*.C*.OS(=O)(=O)C1=CC=CC=C1 |c:8,10,t:6,lp:4:2...
64  [Na+].[Na+].[Na+].[Na+].OO.OO.OO.[O-]C([O-])=O...
79  [Na+].[Na+].OC(=O)CN(CCN(CC(O)=O)CC([O-])=O)CC...
단일 구조가 아닌 물질 개수: 13

In [28]:
# 단일 구조만 남기기

df_single = df[
    ~df['SMILES'].str.contains(r'\.', regex=True)
]

print(df.shape)
print(df_single.shape)

print(df_single['label'].value_counts())

(81, 26)
(68, 26)
label
0    47
1    21
Name: count, dtype: int64

In [29]:
# 최종 저장

df_single.to_csv(
    'skin_irritation_single.csv',
    index=False
)

print('저장 완료!')

저장 완료!

In [30]:
df_final.to_csv(
    'skin_irritation_descriptor.csv',
    index=False
)

print('descriptor 저장 완료!')

descriptor 저장 완료!

In [31]:
df_fp_final = pd.concat([df_id, df_fp], axis=1)

df_fp_final.to_csv(
    'skin_irritation_fingerprint.csv',
    index=False
)

print('fingerprint 저장 완료!')

fingerprint 저장 완료!

In [26]:
'''
descriptor 추가로 계산하는 방법 (https://github.com/marcabrus/VegaDescriptor-Calculation)
모델 성능을 올리기 위해 다양한 descriptor 계산 필요.

1. Descriptors vega.zip 다운받기 ( <> Code -> Download ZIP )
2. 실행 파일: prompt
(sublime으로 열어서 명령어 살펴보기, 명령어 설명은 spiegazione prompt.txt에 기재되어 있음.)
3. input 예시 (molecules.txt)
4. output 예시 (out.txt)
'''

'\ndescriptor 추가로 계산하는 방법 (https://github.com/marcabrus/VegaDescriptor-Calculation)\n모델 성능을 올리기 위해 다양한 descriptor 계산 필요.\n\n1. Descriptors vega.zip 다운받기 ( <> Code -> Download ZIP )\n2. 실행 파일: prompt\n(sublime으로 열어서 명령어 살펴보기, 명령어 설명은 spiegazione prompt.txt에 기재되어 있음.)\n3. input 예시 (molecules.txt)\n4. output 예시 (out.txt)\n'